version: '3.1'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-auth
    ports:
      - '4003:4003'
    restart: on-failure
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 'secret'
      MYSQL_DATABASE: 'bd_auth'
    volumes:
      - .:/usr/src/
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.13
    container_name: mysql-auth
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
      - '3306:3306'
    volumes:
      - ~/docker/mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'bd_auth'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'secret'
